[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "music_genres"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "torch>=2.0.0",
    "numpy>=2.4.4",
    "torchaudio>=2.0.0",
    "kagglehub",
    "soundfile",
    "matplotlib>=3.10.9",
    "ipykernel>=7.2.0",
]

[project.scripts]
music_genres = "music_genres.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/music_genres"]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

# [tool.uv.sources]
# torch = { index = "pytorch-cpu" }
# torchaudio = { index = "pytorch-cpu" }
